server:
  port: ${SERVER_PORT:8080}
  servlet:
    contextPath: "/tracker"

spring:
  application:
    name: music-tracker-backend

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:${DATABASE_PORT:5432}/trackerdb?ssl=false
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource


spotify:
  api-base-url: https://api.spotify.com
  auth-url: https://accounts.spotify.com/api/token
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

app:
  storage:
    location: ${STORAGE_LOCATION:./local-storage/covers}